/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yFrame;

import AppPackage.AnimationClass;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMinimizar = new javax.swing.JLabel();
        jlblCerrar = new javax.swing.JLabel();
        jlblPalo = new javax.swing.JLabel();
        jlblPalo2 = new javax.swing.JLabel();
        jlblPublicidad1 = new javax.swing.JLabel();
        jlblPublicidad2 = new javax.swing.JLabel();
        jBBack = new javax.swing.JButton();
        jBNext = new javax.swing.JButton();
        jlblBackgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jlblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMinimizarMouseClicked(evt);
            }
        });
        jPanel1.add(jlblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        jlblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Delete_32px.png"))); // NOI18N
        jlblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(jlblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jlblPalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paloPublic.png"))); // NOI18N
        jPanel1.add(jlblPalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 94, 1000, 10));

        jlblPalo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paloPublic.png"))); // NOI18N
        jPanel1.add(jlblPalo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 418, 1000, 10));

        jlblPublicidad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/publi1.png"))); // NOI18N
        jPanel1.add(jlblPublicidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, -1));

        jlblPublicidad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/publi2.png"))); // NOI18N
        jPanel1.add(jlblPublicidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 1000, -1));

        jBBack.setBackground(new java.awt.Color(0, 0, 0));
        jBBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BACK.png"))); // NOI18N
        jBBack.setBorder(null);
        jBBack.setBorderPainted(false);
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(948, 440, -1, -1));

        jBNext.setBackground(new java.awt.Color(0, 0, 0));
        jBNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NEXT.png"))); // NOI18N
        jBNext.setBorder(null);
        jBNext.setBorderPainted(false);
        jBNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBNextMouseClicked(evt);
            }
        });
        jBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextActionPerformed(evt);
            }
        });
        jPanel1.add(jBNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 440, -1, -1));

        jlblBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Login.png"))); // NOI18N
        jPanel1.add(jlblBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        
        AnimationClass ac1 = new AnimationClass();
        ac1.jLabelXRight(-1000, 0, 25, 5, jlblPublicidad1);
        
        AnimationClass ac2 = new AnimationClass();
        ac2.jLabelXRight(0, 1000, 25, 5, jlblPublicidad2);
    }//GEN-LAST:event_jBBackActionPerformed

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBNextActionPerformed

    private void jBNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMouseClicked
        AnimationClass ac1 = new AnimationClass();
        ac1.jLabelXLeft(0, -1000, 25, 5, jlblPublicidad1);
        
        AnimationClass ac2 = new AnimationClass();
        ac2.jLabelXLeft(1000, 0, 25, 5, jlblPublicidad2);
    }//GEN-LAST:event_jBNextMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AnimationClass ac1 = new AnimationClass();
        ac1.jLabelXLeft(0, -1000, 25, 5, jlblPublicidad1);
        
        AnimationClass ac2 = new AnimationClass();
        ac2.jLabelXLeft(1000, 0, 25, 5, jlblPublicidad2);
    }//GEN-LAST:event_formWindowOpened

    private void jlblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizarMouseClicked
        this.setState(yFrame.Login.ICONIFIED);
    }//GEN-LAST:event_jlblMinimizarMouseClicked

    private void jlblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCerrarMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar el sistema?", "EXIT", dialogButton);
            if (result == 0) {
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jlblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblBackgroud;
    private javax.swing.JLabel jlblCerrar;
    private javax.swing.JLabel jlblMinimizar;
    private javax.swing.JLabel jlblPalo;
    private javax.swing.JLabel jlblPalo2;
    private javax.swing.JLabel jlblPublicidad1;
    private javax.swing.JLabel jlblPublicidad2;
    // End of variables declaration//GEN-END:variables
}
